name: "Hame Relay (v154 Test)"
version: "1.3.0-beta"
slug: "hame_relay_test"
description: "TEST VERSION: Hame Relay with v154+ firmware XID dual-format support"
url: "https://github.com/rweijnen/hame-relay-test"
image: "ghcr.io/rweijnen/hame-relay-test-addon:latest"
arch:
  - armv7
  - aarch64
  - amd64
init: false
startup: application
boot: auto
services:
  - mqtt:need
watchdog: "http://[HOST]:[PORT:8080]/health"
options:
  inverse_forwarding: false
  default_broker_id: hame-2024
  log_level: info
  devices:
    - device_id: "24-digit-device-id"
      mac: "maccaddresswithoutcolons"
      type: "HMA-1"
      version: 0
schema:
  mqtt_uri: str?
  inverse_forwarding: bool?
  default_broker_id: list(hame-2024|hame-2025)?
  log_level: list(trace|debug|info|warn|error|fatal)?
  username: str?
  password: password?
  devices:
    - device_id: str
      mac: str
      type: str
      version: int?
      inverse_forwarding: bool?
